
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwxesdupbzdcnknaupuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3eGVzZHVwYnpkY25rbmF1cHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1ODkzODIsImV4cCI6MjA1NzE2NTM4Mn0.eRZ0inq2ZtJjbfbDQwW_G2TBeA_NDnap3lZt44as5dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    global: {
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
    },
    auth: {
      persistSession: true
    },
    db: {
      schema: 'public'
    }
  }
);
